### ISSUE TITLE
Autoconf issues on ArchLinux

### ISSUE THREAD

**Issue by bjoernd** [vmt/udis86#6]
Trying to build udis86 on recent ArchLinux fails during the autoconf phase:

$> ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR,`build'.
libtoolize: copying file `build/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR,`m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file`m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file`m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
automake: warnings are treated as errors
/usr/share/automake-1.13/am/ltlibrary.am: warning: 'libudis86.la': linking libtool libraries using a non-POSIX
/usr/share/automake-1.13/am/ltlibrary.am: archiver requires 'AM_PROG_AR' in 'configure.ac'
libudis86/Makefile.am:8:   while processing Libtool library 'libudis86.la'
tests/Makefile.am:58: warning: call oprtest_generate,64: non-POSIX variable name
tests/Makefile.am:58: (probably a GNU make extension)
tests/Makefile.am:59: warning: call oprtest_generate,32: non-POSIX variable name
tests/Makefile.am:59: (probably a GNU make extension)
tests/Makefile.am:60: warning: call oprtest_generate,16: non-POSIX variable name
tests/Makefile.am:60: (probably a GNU make extension)
tests/Makefile.am:117: warning: call diff_test_asm,"diff": non-POSIX variable name
tests/Makefile.am:117: (probably a GNU make extension)
tests/Makefile.am:122: warning: call diff_test_asm,"refup": non-POSIX variable name
tests/Makefile.am:122: (probably a GNU make extension)
autoreconf: automake failed with exit status: 1
autogen: autoreconf -i failed.

$> autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
http://gnu.org/licenses/gpl.html, http://gnu.org/licenses/exceptions.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.

$>  automake --version
automake (GNU automake) 1.13.1
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later http://gnu.org/licenses/gpl-2.0.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey tromey@redhat.com
       and Alexandre Duret-Lutz adl@gnu.org.

This behavior seems to stem from a change that came in automake 1.12 according to http://lists.gnu.org/archive/html/bug-automake/2012-05/msg00009.html

**Comment by thebodzio** [comment]
The first problem

/usr/share/automake-1.13/am/ltlibrary.am: warning: 'libudis86.la': linking libtool libraries using a non-POSIX
/usr/share/automake-1.13/am/ltlibrary.am: archiver requires 'AM_PROG_AR' in 'configure.ac'

is indeed due to changes in automake. It can be fixed by placing

m4_ifdef([AM_PROG_AR], [AM_PROG_AR])

in configure.ac (http://lists.gnu.org/archive/html/automake/2012-05/msg00014.html).

About the second problem (the “tests”): I made udis86-git package available via AUR (https://aur.archlinux.org/packages/udis86-git/), where I simply commented out problematic lines in tests/Makefile.am (58, 59, 60, 117, 122). I just don't know what they supposed to do exactly, but since I decided to not to do any post-build tests I don't need them. I thinks these lines were intended to call some python methods/functions, however I wasn't able to find such methods in python scripts in repo.

**Comment by vmt** [comment]
Closing for now. I believe Bjoern's change fixes this. Please re-open if this is still a problem.
